name: Rust Build and Release
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Moved permissions to top level

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose --release

    - name: Upload Linux Artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifacts
        path: target/release/libdbl_validator.so

    - name: Upload Windows Artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifacts
        path: |
          target/release/dbl_validator.dll
          target/release/dbl_validator.pdb

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/download-artifact@v4
      with:
        name: linux-artifacts
        path: linux
    
    - uses: actions/download-artifact@v4
      with:
        name: windows-artifacts
        path: windows

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          linux/libdbl_validator.so
          windows/dbl_validator.dll
          windows/dbl_validator.pdb
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}